# Generated by Django 2.1.1 on 2018-10-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ja', models.CharField(default='', max_length=255, verbose_name='空港名：日本語')),
                ('name_en', models.CharField(default='', max_length=255, verbose_name='空港名：英語')),
                ('iata', models.CharField(default='', max_length=3, verbose_name='IATA')),
                ('icao', models.CharField(default='', max_length=4, verbose_name='ICAO')),
                ('coordinate_latitude', models.FloatField(default=0, verbose_name='座標：緯度')),
                ('coordinate_longitude', models.FloatField(default=0, verbose_name='座標：経度')),
                ('open_time', models.TimeField(blank=True, verbose_name='営業時間：開始')),
                ('close_time', models.TimeField(blank=True, verbose_name='営業時間：終了')),
                ('num_terminals', models.IntegerField(default=0, verbose_name='ターミナル数')),
                ('area_breadth', models.CharField(blank=True, default='', max_length=255, verbose_name='敷地面積')),
                ('url', models.URLField(blank=True, default='', verbose_name='WebサイトURL')),
                ('main_image', models.ImageField(blank=True, upload_to='static/img/airport/main', verbose_name='メイン画像')),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='country.Country', verbose_name='国')),
            ],
            options={
                'verbose_name': '空港',
                'verbose_name_plural': '空港',
            },
        ),
    ]
