# Generated by Django 2.0.2 on 2018-09-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='airport_code',
            field=models.CharField(default='', max_length=4, verbose_name='空港コード'),
        ),
    ]
