# Generated by Django 2.0.2 on 2018-09-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_airport_airport_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='airport_code',
        ),
        migrations.AddField(
            model_name='airport',
            name='iata',
            field=models.CharField(default='', max_length=2, verbose_name='IATA'),
        ),
        migrations.AddField(
            model_name='airport',
            name='icao',
            field=models.CharField(default='', max_length=3, verbose_name='ICAO'),
        ),
    ]
