# Generated by Django 2.0.2 on 2018-09-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_auto_20180906_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='location',
        ),
    ]
