# Generated by Django 2.0.2 on 2018-09-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_remove_airport_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='establish_date',
            field=models.DateField(blank=True, verbose_name='設立日'),
        ),
    ]
