# Generated by Django 2.0.2 on 2018-09-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_auto_20180906_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='establish_date',
        ),
    ]
