# Generated by Django 2.0.2 on 2018-09-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_remove_airport_establish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata',
            field=models.CharField(default='', max_length=3, verbose_name='IATA'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='icao',
            field=models.CharField(default='', max_length=4, verbose_name='ICAO'),
        ),
    ]
