# Generated by Django 2.0.2 on 2018-09-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0007_auto_20180906_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='area_breadth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='敷地面積'),
        ),
    ]
