# Generated by Django 2.0.2 on 2018-09-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0009_auto_20180906_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='area_breadth',
            field=models.CharField(default='', max_length=255, verbose_name='敷地面積'),
        ),
    ]
