# Generated by Django 2.0.2 on 2018-09-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0010_auto_20180906_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='area_breadth',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='敷地面積'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='close_time',
            field=models.TimeField(blank=True, verbose_name='営業時間：終了'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='open_time',
            field=models.TimeField(blank=True, verbose_name='営業時間：開始'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='WebサイトURL'),
        ),
    ]
