# Generated by Django 2.0.2 on 2018-09-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ja', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('code_two', models.CharField(max_length=2)),
                ('code_three', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': '国',
                'verbose_name_plural': '国',
            },
        ),
    ]
