# Generated by Django 2.0.2 on 2018-09-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code_three',
            field=models.CharField(max_length=3, verbose_name='国名コード：3桁'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code_two',
            field=models.CharField(max_length=2, verbose_name='国名コード：2桁'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='国名：英語'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_ja',
            field=models.CharField(max_length=255, verbose_name='国名：日本語'),
        ),
    ]
