# Generated by Django 2.0.2 on 2018-09-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180930_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.TextField(blank=True, verbose_name='自己紹介'),
        ),
    ]
