# Generated by Django 2.0.2 on 2018-09-05 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0003_alliance_url'),
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='member_alliance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='alliance.Alliance', verbose_name='加盟アライアンス'),
        ),
    ]
