# Generated by Django 2.0.2 on 2018-09-05 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_airline_member_alliance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airline',
            options={'verbose_name': '航空会社', 'verbose_name_plural': '航空会社'},
        ),
    ]
