# Generated by Django 2.0.2 on 2018-09-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='main_image',
            field=models.ImageField(upload_to='static/img/alliance', verbose_name='ロゴ画像'),
        ),
    ]
