# Generated by Django 2.0.2 on 2018-09-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0002_auto_20180905_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='url',
            field=models.URLField(default='', verbose_name='WebサイトURL'),
        ),
    ]
