# Generated by Django 2.0.2 on 2018-11-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0001_initial'),
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_flag', models.CharField(choices=[('0', '無効'), ('1', '有効')], default='0', max_length=2, verbose_name='自由名称フラグ：ラウンジ名の日本語・英語を利用する場合は有効化')),
                ('name_ja', models.CharField(blank=True, default='', max_length=255, verbose_name='ラウンジ名：日本語')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='ラウンジ名：英語')),
                ('main_image', models.ImageField(blank=True, upload_to='static/img/lounge/main', verbose_name='メイン画像')),
                ('airline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airline.Airline', verbose_name='航空会社')),
                ('airport', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='airport.Airport', verbose_name='空港')),
            ],
            options={
                'verbose_name': 'ラウンジ',
                'verbose_name_plural': 'ラウンジ',
            },
        ),
    ]
