# Generated by Django 2.1.1 on 2018-11-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lounge', '0002_lounge_alliance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lounge',
            name='alliance',
        ),
    ]
