# Generated by Django 2.1.1 on 2018-10-23 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import review.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_synthesis', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=2, verbose_name='総合評価')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('review_update', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('review_title', models.CharField(default='', max_length=40, verbose_name='タイトル')),
                ('review_text', models.TextField(default='', max_length=1000, verbose_name='レビュー')),
                ('review_img_01', models.FileField(blank=True, upload_to=review.models.get_upload_path, verbose_name='画像1')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Airport', verbose_name='空港')),
                ('user', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
