# Generated by Django 2.1.1 on 2018-10-02 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0011_auto_20180907_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_clean', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=None, max_length=1, verbose_name='清潔さ')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Airport', verbose_name='空港')),
            ],
        ),
    ]
