# Generated by Django 2.1.1 on 2018-10-09 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_clean', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=None, max_length=2, verbose_name='清潔さ')),
                ('rate_facility', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=None, max_length=2, verbose_name='施設・設備')),
                ('rate_lounge', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=None, max_length=2, verbose_name='ラウンジ')),
                ('rate_service', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=None, max_length=2, verbose_name='サービス')),
                ('rate_access', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=None, max_length=2, verbose_name='アクセス')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('review_update', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('review_title', models.CharField(default='', max_length=40, verbose_name='タイトル')),
                ('review_text', models.TextField(default='', max_length=1000, verbose_name='レビュー')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Airport', verbose_name='空港')),
            ],
        ),
    ]
