# Generated by Django 2.1.1 on 2018-10-22 08:52

from django.db import migrations, models
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_img_01',
            field=models.FileField(blank=True, upload_to=review.models.get_upload_path, verbose_name='画像1'),
        ),
    ]
