# Generated by Django 2.1.1 on 2018-11-05 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lounge', '0003_remove_lounge_alliance'),
        ('review', '0002_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='airport',
        ),
        migrations.AddField(
            model_name='review',
            name='lounge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lounge.Lounge', verbose_name='ラウンジ'),
        ),
    ]
