# Generated by Django 2.1.1 on 2018-10-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20181002_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate_access',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('1', '10')], default=None, max_length=2, verbose_name='アクセス'),
        ),
        migrations.AddField(
            model_name='review',
            name='rate_facility',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('1', '10')], default=None, max_length=2, verbose_name='施設・設備'),
        ),
        migrations.AddField(
            model_name='review',
            name='rate_lounge',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('1', '10')], default=None, max_length=2, verbose_name='ラウンジ'),
        ),
        migrations.AddField(
            model_name='review',
            name='rate_service',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('1', '10')], default=None, max_length=2, verbose_name='サービス'),
        ),
    ]
