# Generated by Django 2.1.1 on 2018-10-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_img_01',
            field=models.ImageField(blank=True, upload_to='', verbose_name='画像1'),
        ),
    ]
