# Generated by Django 2.0.2 on 2018-10-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate_synthesis',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=2, verbose_name='総合評価'),
        ),
    ]
