# Generated by Django 2.1.1 on 2018-10-03 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20181003_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登録日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(default=None, max_length=1000, verbose_name='レビュー'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default=None, max_length=40, verbose_name='タイトル'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_update',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
